name: pokedex_cleanarch
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  google_fonts: ^3.0.1
  brasil_fields: ^1.8.0
  shimmer: ^2.0.0
  dio: ^4.0.6
  connectivity_plus: ^2.3.2
  flutter_secure_storage: ^7.0.0
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  mobx_codegen: ^2.1.1
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: SevenSegment
      fonts:
        - asset: assets/fonts/seven_segments.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf

    - family: Pokemon
      fonts:
        - asset: assets/fonts/PokemonSolid.ttf
          weight: 900

    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/PokemonHollow.ttf
          weight: 200
